export enum CHANNELS {
  DIRECTORY_PICKER_OPEN = `DIRECTORY_PICKER_OPEN`,
  REDUX_STORE_CLEAR = `REDUX_STORE_CLEAR`,
  REDUX_STORE_INITIALIZE = `REDUX_STORE_INITIALIZE`,
  REDUX_STORE_PERSIST = `REDUX_STORE_PERSIST`,
}
