export enum CHANNELS {
  DIRECTORY_PICKER_OPEN = `DIRECTORY_PICKER_OPEN`,
  HTTP_MAKE_REQUEST = `HTTP_MAKE_REQUEST`,
  NAVIGATION = `NAVIGATION`,
  REDUX_STORE_CLEAR = `REDUX_STORE_CLEAR`,
  REDUX_STORE_INITIALIZE = `REDUX_STORE_INITIALIZE`,
  REDUX_STORE_PERSIST = `REDUX_STORE_PERSIST`,
  REDUX_STORE_RESET_FROM_MAIN_PROCESS = `REDUX_STORE_RESET_FROM_MAIN_PROCESS`,
}
