export enum CHANNELS {
  FILE_SYSTEM_HTTP_REQUEST_CHANGED = `FILE_SYSTEM_HTTP_REQUEST_CHANGED`,
  DIRECTORY_PICKER_OPEN = `DIRECTORY_PICKER_OPEN`,
  HTTP_MAKE_REQUEST = `HTTP_MAKE_REQUEST`,
  HTTP_REQUESTS_CHANGE_METHOD = `HTTP_REQUESTS_CHANGE_METHOD`,
  HTTP_REQUESTS_CHANGE_URL = `HTTP_REQUESTS_CHANGE_URL`,
  HTTP_REQUESTS_CREATE = `HTTP_REQUESTS_CREATE`,
  NAVIGATION = `NAVIGATION`,
  REDUX_STORE_CLEAR = `REDUX_STORE_CLEAR`,
  REDUX_STORE_INITIALIZE = `REDUX_STORE_INITIALIZE`,
  REDUX_STORE_PERSIST = `REDUX_STORE_PERSIST`,
  REDUX_STORE_RESET_FROM_MAIN_PROCESS = `REDUX_STORE_RESET_FROM_MAIN_PROCESS`,
  WORKSPACES_CREATE_DIRECTORY = `WORKSPACES_CREATE_DIRECTORY`,
}
