export const CONTEXT_BRIDGE_EVENT_NAMES = {
  RESIZE_WINDOW: 'RESIZE_WINDOW',
  QUIT_APP: `QUIT_APP`,
  OPEN_DIRECTORY_PICKER: `OPEN_DIRECTORY_PICKER`,
  RESET_STORE: `RESET_STORE`,
  CHOOSE_WORKSPACE: `CHOOSE_WORKSPACE`,
  INITIALIZE_REDUX_STORE: `INITIALIZE_REDUX_STORE`,
  PERSIST_REDUX_STORE: `PERSIST_REDUX_STORE`,
} as const
